### ISSUE TITLE
Double-click on a card ends up with an exception

### ISSUE THREAD

**Issue by nadzyah** [canonical/test_observer#131]
Current behaviour: When you double click on a card (for instance, to select the card name like you can select text on other websites), it returns the exception `GoException: no routes for location: /snaps/:artefactId/<artefact_id>`

[Screencast from 27-02-24 17:24:32.webm](https://github.com/canonical/test_observer/assets/84857215/3b5cda65-a380-4eca-b42e-ed8c76e6cf6a)

Expected behaviour: I guess it would be great to allow users to select the the whole string like card name, store, version by double-clicking on its name. Alternatively, we can just open a card instead of returning an error

**Comment by omar-selo** [comment]
I tried reproducing this on different browsers but I couldn't. I wonder if there is some precondition for it to occur.

**Comment by nadzyah** [comment]
> I tried reproducing this on different browsers but I couldn't. I wonder if there is some precondition for it to occur.

I'm using Google Chrome here, but let me try with Firefox
