### ISSUE TITLE
no way to filter and ctrl+f does not work

### ISSUE THREAD

**Issue by xnox** [canonical/test_observer#71]
I wanted to quickly find pc-kernel snap.

There is no filter to type `pc-kernel` to filter everything by pc-kernel.

I instead pressed `ctrl+f` and tried to search for pc-kernel, but somehow that doesn't work, as it brings up nothing.

**Comment by omar-selo** [comment]
Thanks for sharing!

The front-end is developed using flutter. So it [doesn't work with native browser ctrl + f](https://github.com/flutter/flutter/issues/65504). We can however definitely consider adding a search bar to help find a particular snap/deb.

**Comment by mz2** [comment]
Ctrl+F doesn't work on CanvasKit based rendering but it should work just fine when HTML rendered (fractional scaling via the browser viewport zoom thing should also work better, I think this had been reported somewhere too).

Should be addressed in https://github.com/canonical/test_observer/issues/71

**Comment by omar-selo** [comment]
After investigation, it seems that while #99 will improve this situation it's important to keep in mind a couple of limitations.
1. The search string can't have any special characters. (i.e. ' ', '_', ':', etc.) as it wouldn't work if it does
2. It can't find anything outside the view. So for instance if you need to scroll to find an artefact, then ctrl+f will not find it

So perhaps this is better addressed through a proper search box

**Comment by xnox** [comment]
I still question why this thing is not designed by the Canonical Web Team using Vanilla CSS framework and responsive design, and instead is done in flutter - when none of our websites ever use flutter.

Is it also supposed to be a desktop app? And does a desktop app for this thing exists - and is the UX any better?

Because so far, this thing is not fit for purpose.

What is the backing data source for the flutter ui? Is it possible to access the database, or download json or yaml data dump of all the results / all the views?

**Comment by omar-selo** [comment]
Currently, there is no desktop app just a web app. But we do have a backend API, namely https://test-observer-api.canonical.com/docs. As for the flutter decision, perhaps @mz2 is better equipped to elaborate on that.

**Comment by omar-selo** [comment]
We've deployed a search box that can be opened via `Ctrl+F`.
